Issues 87 and 72
DevProgress/my-vote-matters pull request #88
Opened 2016-11-04 00:53 UTC by Burtchen

This should address two issues:

- issue #87 : make the initial message on iOS less confusing by going for our core "Share why YOUR vote matters" rather than "oops" right from the beginning - after all, the next thing the user sees is an option to upload/take a picture as provided by iOS
- issue #72 when checking for canvas resizing, also check whether controls (buttons, inputs...) are visible - if not, which should be edge cases, put them in the top of the canvas area

Things to consider:
- Some real-life iOS testing would be great
- I don't think it makes too much sense now, but the controls re-positioning function could also have an option to reset items to their original spot if the user has enlarged the window

2016-11-04 04:44 UTC, dglazkov requested changes
I took a quick look, a couple of comments.

2016-11-04 04:44 UTC, dglazkov commented on js/main.js
> +    var noCameraText = iOS ? 'Share why YOUR vote matters!' : 'Oops! It looks like your camera won\'t work here, but you can upload a photo instead by pressing the button below.';
For camera-less computers, the message is flowing underneath the button here.

2016-11-04 04:44 UTC, dglazkov commented on js/main.js
> +    if (localstream && typeof localstream.getTracks === "function") {
Where does `localstream` come from?

2016-11-04 11:49 UTC, Burtchen commented on js/main.js
> +    if (localstream && typeof localstream.getTracks === "function") {
Localstream is assigned from `stream`  in the `getUserMedia` callback and initially defined as `null`. This is how we actually stop the camera itself.

2016-11-05 14:33 UTC, Burtchen commented
Issues should be fixed now.

2016-11-05 14:34 UTC, merged